---
#
# 使い方:
#   TARGET_HOST=10.x.x.x
#   MAIN_USERNAME=username
#   MAIN_PASSWORD=password
#   DOCROOT=/var/www/html/htdocs
#   PERMIT_NETWORK=10.0.0.0/8
#   CAKE_ENV_MODE=development
#   env ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i "${TARGET_HOST}:22," -u root -k site.yml \
#     --extra-vars "main_username=${MAIN_USERNAME} main_password=`openssl passwd -salt salty -1 ${MAIN_PASSWORD}` docroot=${DOCROOT} permit_network=${PERMIT_NETWORK} cake_env_mode=${CAKE_ENV_MODE}"
# 備考:
#   - TARGET_HOSTは設定対象のホストのIPアドレスを指定してください
#     rootでsshに接続しようとします
#   - MAIN_USERNAMEで指定した名前のユーザ・グループが作成されます
#     パスワードはMAIN_PASSWORDの値になります
#   - DOCROOTで指定したディレクトリがApacheのDocumentRootとなります
#     ディレクトリの所有者・所有グループはMAIN_USERNAMEで指定したものになります
#   - CAKE_ENV_MODEで指定した値が環境変数CAKE_ENV_MODEの値に設定されます
#   - PERMIT_NETWORKで指定したネットワーク範囲からPostgreSQLに接続可能です
#   - PostgreSQLにはID/PASS:postgre/postgresでアクセスできます
#   - 実行後は一度再起動してください
#
- name: for CakePHP on LAPP (CentOS 7.1.1503, PostgreSQL 9.4, PHP 7.0-dev) Ver. 20150414
  hosts: all
  user: root
  roles:
    - { role: centos7-common, main_username: "{{ main_username }}", main_password: "{{ main_password }}" }
    - { role: centos7-apache, main_username: "{{ main_username }}", docroot: "{{ docroot }}", cake_env_mode: "{{ cake_env_mode }}" }
    - { role: centos7-remi-php70 }
    - { role: centos7-pgdg-postgresql94, permit_network: "{{ permit_network }}" }
